# Shape manipulation in matrix

In [1]:
import numpy as np

### Redefine matrix dimension

In [2]:
arr_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [3]:
arr_2d.shape

(2, 4)

In [8]:
# Reshape 2x4 matrix to 2x2x2 matrix
arr_3d = arr_2d.reshape(2, 2, 2)

In [9]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Transform matrix into vector

In [10]:
random_arr_3d = np.random.random((3, 3, 3))

In [11]:
random_arr_3d

array([[[0.00215257, 0.85865488, 0.02376017],
        [0.64600895, 0.00100766, 0.3641085 ],
        [0.18850991, 0.48166822, 0.88916415]],

       [[0.79775479, 0.82478833, 0.42065753],
        [0.68196844, 0.22927758, 0.1149541 ],
        [0.26126805, 0.837752  , 0.9815672 ]],

       [[0.12528516, 0.80427254, 0.30228636],
        [0.94647814, 0.15445853, 0.28574624],
        [0.66881212, 0.02711146, 0.61186087]]])

In [14]:
# Turn matrix into vector
flattened_random_arr = random_arr_3d.flatten()

In [15]:
flattened_random_arr

array([0.00215257, 0.85865488, 0.02376017, 0.64600895, 0.00100766,
       0.3641085 , 0.18850991, 0.48166822, 0.88916415, 0.79775479,
       0.82478833, 0.42065753, 0.68196844, 0.22927758, 0.1149541 ,
       0.26126805, 0.837752  , 0.9815672 , 0.12528516, 0.80427254,
       0.30228636, 0.94647814, 0.15445853, 0.28574624, 0.66881212,
       0.02711146, 0.61186087])

In [16]:
flattened_random_arr.shape

(27,)

### Extend matrix dimension

In [27]:
numbers_2D = np.array(([1,2,3],[4,5,6]))
numbers_2D.shape

(2, 3)

In [28]:
numbers_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# Increase matrix dimension from n to n+1 -> axis = 0 means row expansion
numbers_3D_axis_0 = np.expand_dims(numbers_2D, axis=0)
numbers_3D_axis_0.shape

(1, 2, 3)

In [38]:
# Matrix has 1 row, each row has 2 columns, each column has a vector of 3 vals
numbers_3D_axis_0

array([[[1, 2, 3],
        [4, 5, 6]]])

In [35]:
# Increase matrix dimension from n to n+1 -> axis = 1 means column expansion
numbers_3D_axis_1 = np.expand_dims(numbers_2D, axis=1)
numbers_3D_axis_1.shape

(2, 1, 3)

In [37]:
# Matrix has 2 rows, each row has 1 column, each column has a vector of 3 vals
numbers_3D_axis_1

array([[[1, 2, 3]],

       [[4, 5, 6]]])

### Reduce matrix dimension

In [44]:
numbers_3D = np.random.random((1, 5, 3))
numbers_3D

array([[[0.50161819, 0.41867128, 0.23907857],
        [0.04529804, 0.07182417, 0.73293005],
        [0.66119383, 0.42361977, 0.99263392],
        [0.36420457, 0.22647299, 0.3708888 ],
        [0.90697416, 0.58164053, 0.25458265]]])

In [46]:
# Deduce matrix dimension
# Axis to be squeezed must have the size of 1
numbers_2D_axis_0 = np.squeeze(numbers_3D, axis=0)

In [48]:
numbers_2D_axis_0.shape

(5, 3)

### Transpose

In [50]:
numbers_2D = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
numbers_2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
numbers_2D.shape

(2, 4)

In [51]:
transposed_numbers_1 = numbers_2D.T
transposed_numbers_1

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [53]:
transposed_numbers_1.shape

(4, 2)

In [54]:
# Another way
transposed_numbers_2 = np.transpose(numbers_2D)
transposed_numbers_2

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [55]:
transposed_numbers_2.shape

(4, 2)