# Vector & Matrix Addition

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 3],
    [1, 0],
    [1, 2]
])

In [3]:
B = np.array([
    [0, 0],
    [7, 5],
    [2, 1]
])

In [4]:
# Summation of A & B matrices
np.add(A, B)

array([[1, 3],
       [8, 5],
       [3, 3]])

In [5]:
# Subtraction of A & B matrices
np.subtract(A,B)

array([[ 1,  3],
       [-6, -5],
       [-1,  1]])

In [6]:
C = np.array([
    [1, 2, 3],
    [3, 2, 1]
])

In [7]:
D = np.array([
    [4, 5, 6],
    [6, 5, 4]
])

In [8]:
np.add(C, D)

array([[5, 7, 9],
       [9, 7, 5]])

In [20]:
E = np.subtract(D, -C)

In [21]:
E = E*-1

In [22]:
E

array([[-5, -7, -9],
       [-9, -7, -5]])