# Scalar & Vector practice

In [2]:
import numpy as np

In [3]:
# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

In [4]:
# Size of array
# 1x5
arr_1d.shape

(5,)

In [5]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
# 2x3 array or matrix
arr_2d.shape

(2, 3)

In [7]:
# 3D array
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
    [[0, -1, -2], [-3, -5, -10]]
])

In [8]:
# 4x2x3 array
arr_3d.shape

(4, 2, 3)

In [9]:
# Create 1D array with 6 components only cotains 0
zero_arr_1d = np.zeros((6, ))

In [10]:
zero_arr_1d

array([0., 0., 0., 0., 0., 0.])

In [11]:
# Create 1D matrix with 6 components only contains 1
one_arr_1d = np.ones((6, ))

In [12]:
one_arr_1d

array([1., 1., 1., 1., 1., 1.])

In [13]:
# Create 1D matrix with 6 components only contains 9
nine_arr_1d = np.full((6, ), 9)

In [14]:
nine_arr_1d

array([9, 9, 9, 9, 9, 9])

In [21]:
# Create an identity nxn matrix
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# Create a vector that contains number from 0 to n - 1
zero_to_number_arr_1d = np.arange(10)

In [31]:
zero_to_number_arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Create a vector that contains number from i to j - 1
continuous_int_number_to_number_arr_1d = np.arange(2, 10)

In [33]:
continuous_int_number_to_number_arr_1d

array([2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Create a vector that contains number from i to j - x where x is the gap between numbers
discontinuous_int_number_to_number_arr_1d = np.arange(2, 10, 2)

In [36]:
discontinuous_int_number_to_number_arr_1d

array([2, 4, 6, 8])

In [37]:
# Create a mxn matrix with random numbers in matrix components
np.random.random((3, 5))

array([[0.27788936, 0.72848893, 0.46016435, 0.16733192, 0.23228167],
       [0.71113941, 0.8246929 , 0.05751218, 0.8331231 , 0.75915666],
       [0.90328684, 0.87121335, 0.40145387, 0.89734944, 0.63417203]])