In [1]:
import numpy as np

In [2]:
a = np.arange(60.).reshape(3,4,5)

In [3]:
a

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]],

       [[20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.]],

       [[40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.],
        [50., 51., 52., 53., 54.],
        [55., 56., 57., 58., 59.]]])

In [4]:
b = np.arange(24.).reshape(4,3,2)

In [5]:
b

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]],

       [[18., 19.],
        [20., 21.],
        [22., 23.]]])

In [6]:
c = np.tensordot(a,b, axes=([0,1],[1,0]))

In [7]:
c

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [8]:
d = np.zeros((5,2))

In [9]:
for i in range(5):
    for j in range(2):
        for k in range(3):
            for n in range(4):
                d[i,j] += a[k,n,i] * b[n,k,j]

In [10]:
d

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

## Enstein Summation

In [11]:
A = np.array([0, 1, 2])

B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [12]:
A[:, np.newaxis] * B

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [13]:
# summation of columns
# 0 = 0 + 0 + 0 + 0
# 22 = 4 + 5 + 6 + 7
# 76 = 16 + 18 + 20 + 22
# 0-axis means summation of rows
# 1-axis means summation of cols
(A[:, np.newaxis] * B).sum(axis=1)

array([ 0, 22, 76])

In [14]:
# A.shape = (3,) || 1x3
# B.shape = (3, 4) || 3x4
# LHS of "->" to label the input arrays
# RHS of "->" to label the intended output array
# A has 1 axis -> labelled as i
# B has 2 axes -> labelled as i & j
# Both A & B has the same label i -> to tell the einsum that this common axis should be multiplied together
# <=> element-wise mult of array A with col of array B
# <=> A[:, np.newaxis] * B
# RHS == i means that the output array should have the same dim of axis i
# <=> output.shape: (3,) || axis=1
np.einsum('i,ij->i', A, B)

array([ 0, 22, 76])

In [15]:
# RHS == i means that the output array should have the same dim of axis j
# <=> output.shape: (4,) || axis=0
np.einsum('i,ij->j', A, B)

array([20, 23, 26, 29])

### Bigger example

In [16]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [5, 5, 5]])

B = np.array([[0, 1, 0],
              [1, 1, 0],
              [1, 1, 1]])

In [17]:
# Normal matrix mult
print(np.einsum('ij,jk->ik', A, B))
print('\n')
C = A.dot(B)
print(C)

[[ 2  3  1]
 [ 4  6  2]
 [10 15  5]]


[[ 2  3  1]
 [ 4  6  2]
 [10 15  5]]


In [18]:
# Normal matrix mult -> sum along 1-axis
print(np.einsum('ij,jk->i', A, B))
print('\n')
print(C.sum(axis=1))

[ 6 12 30]


[ 6 12 30]


In [19]:
# Normal matrix mult -> sum along 0-axis
print(np.einsum('ij,jk->k', A, B))
print('\n')
print(C.sum(axis=0))

[16 24  8]


[16 24  8]
